name: laptop_recommendation
description: pa mobile
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  babstrap_settings_screen: ^0.1.6
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.6
  cupertino_radio_choice: ^1.0.2
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.3
  firebase_ui_auth: ^1.10.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: 1.0.4
  intl: ^0.18.1
  introduction_screen: ^3.1.12
  path_provider: ^2.1.1

dev_dependencies:
  analyzer: 6.2.0
  build_runner: ^2.0.4
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
