// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVwVx16jOpPV0fQ_eWDHFrRDIbzexH71Y',
    appId: '1:739510096935:web:92d8a54c5fc87f7ab06a02',
    messagingSenderId: '739510096935',
    projectId: 'rekomendasilaptop-5a9f7',
    authDomain: 'rekomendasilaptop-5a9f7.firebaseapp.com',
    storageBucket: 'rekomendasilaptop-5a9f7.appspot.com',
    measurementId: 'G-F9V1RSEESC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH9fARvkfVz3BWn66Vl6kPwljTbahdGqo',
    appId: '1:739510096935:android:9dd975a90c9ec0ebb06a02',
    messagingSenderId: '739510096935',
    projectId: 'rekomendasilaptop-5a9f7',
    storageBucket: 'rekomendasilaptop-5a9f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeHkIpXT7wCxbtR_rwR6UxgXsjINdblLY',
    appId: '1:739510096935:ios:5f1e5ff501f80a23b06a02',
    messagingSenderId: '739510096935',
    projectId: 'rekomendasilaptop-5a9f7',
    storageBucket: 'rekomendasilaptop-5a9f7.appspot.com',
    iosBundleId: 'com.example.laptop_recommendation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeHkIpXT7wCxbtR_rwR6UxgXsjINdblLY',
    appId: '1:739510096935:ios:467f8b01ed6812f5b06a02',
    messagingSenderId: '739510096935',
    projectId: 'rekomendasilaptop-5a9f7',
    storageBucket: 'rekomendasilaptop-5a9f7.appspot.com',
    iosBundleId: 'com.example.laptop_recommendation.RunnerTests',
  );
}
